---
title: 'Homework #5'
author: "April Johns"
date: "2025-11-12"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r fig.width = 13, fig.height = 3.5}
library(tidyverse)

homicides_raw <- read_csv('../data/homicide-data.csv')

homicides_baltimore <- homicides_raw %>% 
  filter(city == 'Baltimore') %>% 
  mutate(reported_date = ymd(reported_date),
         month = month(reported_date),
         year = year(reported_date),
         year_month = make_date(year, month),
         season = if_else(month %in% c(11, 12, 1, 2, 3, 4), 
                          'Winter','Summer'))

homicides_baltimore_loess <- homicides_baltimore %>% 
  group_by(year_month) %>% 
  count()

freddie_gray_arrest <- tibble(arrest_date = mdy('04-12-2015')) %>% 
  mutate(year_month = make_date(year(arrest_date),
                                month(arrest_date)))

homicides_baltimore_plot <- homicides_baltimore %>% 
  ggplot() +
  geom_bar(aes(x = year_month, fill = season)) + 
  geom_smooth(data = homicides_baltimore_loess, 
              aes(x = year_month, y = n), 
              method = 'loess', se = FALSE, span = 0.1) +
  geom_vline(data = freddie_gray_arrest, 
             aes(xintercept = year_month),
             linetype = 50, linewidth = 1.5, color = 'red') +
  geom_text(data = freddie_gray_arrest, 
            aes(x = year_month), y = 40, hjust = 1.05, 
            color = 'lightgrey', size = 5,
            label = "Arrest of \nFreddie Gray") + 
  theme_dark() +
  labs(x = 'Date', y = 'Monthly homicides') + 
  ggtitle('Homicides in Baltimore, MD') +
  theme(legend.position = 'bottom',
        legend.title =  element_blank(),
        plot.title = element_text(size = 18),
        axis.title = element_text(size = 15)) + 
  scale_fill_manual(values = c('Summer' = 'lightgrey', 
                               'Winter' = 'lightblue')) 

homicides_baltimore_plot
```
